### ISSUE TITLE
when set any null value are passing as string

### ISSUE THREAD

**Issue by christiancazu** [Lugriz/object-to-form#2]
//index.js
//....row 12

f.set(levelProp, obj[k]);

When comes any null value there is setting as string, i mean "null".
I trying momentarily this:

f.set(levelProp, obj[k] === null ? '' : obj[k])

that replacement is working fine, but is right?

**Comment by Lugriz** [comment]
Thanks for using the package, I'll fix the issue.

**Comment by Lugriz** [comment]
The issue is solved, a new version is done!
